name: Worldjoincommands
version: '${project.version}'
main: me.jurian.worldjoincommands.worldjoincommands.Worldjoincommands
authors: [ Jurian ]
description: A plugin which executes a command when a player joins a world.
softdepend: [PlaceholderAPI]
commands:
  worldjoincommands:
    usage: "Usage: /<command> <argument>"
    description: The main command of WorldJoinCommands.
    aliases: [wjc]